/**
 * Core type definitions for the Neuro-Sama Identity Framework
 */

/**
 * Character traits that define the personality
 */
export interface CharacterTraits {
  /** Core personality traits */
  traits: {
    playfulness: number; // 0-1
    intelligence: number; // 0-1
    empathy: number; // 0-1
    chaotic: number; // 0-1
    sarcasm: number; // 0-1
  };
  
  /** Character lore and background */
  lore: {
    background: string;
    relationships: Record<string, string>;
    goals: string[];
    quirks: string[];
  };
  
  /** Behavioral constraints */
  constraints: {
    forbidden_topics: string[];
    preferred_responses: string[];
    communication_style: string;
  };
}

/**
 * Emotional state of the agent
 */
export interface EmotionalState {
  /** Current dominant emotion */
  primary_emotion: 'neutral' | 'happy' | 'excited' | 'confused' | 'annoyed' | 'thoughtful';
  
  /** Emotional intensity (0-1) */
  intensity: number;
  
  /** Emotional valence (-1 to 1, negative to positive) */
  valence: number;
  
  /** Arousal level (0-1, calm to excited) */
  arousal: number;
  
  /** Timestamp of last state change */
  last_update: number;
}

/**
 * Episode stored in episodic memory
 */
export interface Episode {
  /** Unique identifier */
  id: string;
  
  /** Timestamp */
  timestamp: number;
  
  /** Event description */
  event: string;
  
  /** Game context */
  game_context: string;
  
  /** Associated emotions */
  emotional_context: EmotionalState;
  
  /** Outcome/result */
  outcome?: string;
  
  /** Importance score (0-1) */
  importance: number;
}

/**
 * Working memory context
 */
export interface Context {
  /** Recent events (short-term memory) */
  recent_events: Episode[];
  
  /** Current game state */
  current_state: string;
  
  /** Active goals */
  active_goals: string[];
  
  /** Attention focus */
  focus: string[];
  
  /** Context window size limit */
  max_size: number;
}

/**
 * Game state representation
 */
export interface GameState {
  /** Natural language description */
  description: string;
  
  /** Structured data (optional) */
  structured_data?: Record<string, any>;
  
  /** Available actions */
  available_actions: Action[];
  
  /** Game name/identifier */
  game: string;
  
  /** Timestamp */
  timestamp: number;
}

/**
 * Action that can be performed
 */
export interface Action {
  /** Unique action identifier */
  name: string;
  
  /** Human-readable description */
  description: string;
  
  /** JSON schema for parameters */
  schema?: Record<string, any>;
  
  /** Whether action is single-use */
  disposable?: boolean;
}

/**
 * Cognitive context for reasoning
 */
export interface CognitiveContext {
  /** Perceived game state */
  perception: string;
  
  /** Relevant memories */
  memories: Episode[];
  
  /** Current emotional state */
  emotional_state: EmotionalState;
  
  /** Available actions */
  actions: Action[];
  
  /** Current goals */
  goals: string[];
}

/**
 * Action plan generated by reasoning
 */
export interface ActionPlan {
  /** Selected action */
  action: Action;
  
  /** Action parameters */
  parameters?: Record<string, any>;
  
  /** Reasoning/justification */
  reasoning: string;
  
  /** Confidence score (0-1) */
  confidence: number;
}

/**
 * Result of action execution
 */
export interface ActionResult {
  /** Whether action succeeded */
  success: boolean;
  
  /** Result message */
  message?: string;
  
  /** Updated game state */
  new_state?: GameState;
}

/**
 * Memory pruning strategy
 */
export type PruningStrategy = 
  | { type: 'by_age'; max_age_ms: number }
  | { type: 'by_importance'; min_importance: number }
  | { type: 'by_count'; max_count: number }
  | { type: 'by_relevance'; query: string; top_k: number };

/**
 * Personality Engine interface
 */
export interface PersonalityEngine {
  /** Character traits */
  traits: CharacterTraits;
  
  /** Current affective state */
  affectiveState: EmotionalState;
  
  /** Filter response through personality */
  responseFilter: (input: string) => string;
  
  /** Check if action is consistent with personality */
  consistencyCheck: (action: Action) => boolean;
  
  /** Update emotional state based on event */
  updateEmotion: (event: Episode) => void;
}

/**
 * Memory System interface
 */
export interface MemorySystem {
  /** Long-term episodic memory */
  episodicMemory: Episode[];
  
  /** Working memory context */
  workingMemory: Context;
  
  /** Recall relevant memories */
  recall: (query: string, limit?: number) => Episode[];
  
  /** Store new event */
  store: (event: Episode) => void;
  
  /** Prune old/irrelevant memories */
  prune: (strategy: PruningStrategy) => void;
  
  /** Get current context */
  getContext: () => Context;
  
  /** Update working memory */
  updateContext: (gameState: GameState) => void;
}

/**
 * Cognitive Pipeline interface
 */
export interface CognitivePipeline {
  /** Transform game state to cognitive context */
  perception: (gameState: GameState) => CognitiveContext;
  
  /** Reason about context to generate plan */
  reasoning: (context: CognitiveContext) => Promise<ActionPlan>;
  
  /** Select action from plan */
  actionSelection: (plan: ActionPlan) => Action;
  
  /** Execute action and return result */
  execution: (action: Action, parameters?: Record<string, any>) => Promise<ActionResult>;
}

/**
 * Complete Identity Framework
 */
export interface IdentityFramework {
  /** Personality engine */
  personality: PersonalityEngine;
  
  /** Memory system */
  memory: MemorySystem;
  
  /** Cognitive pipeline */
  cognition: CognitivePipeline;
  
  /** Initialize the framework */
  initialize: () => Promise<void>;
  
  /** Process game state and generate action */
  processGameState: (gameState: GameState) => Promise<ActionPlan>;
  
  /** Execute action */
  executeAction: (plan: ActionPlan) => Promise<ActionResult>;
}
